data()
rm(list=ls())
data()
dim(mtcars)
head(mtcars,32)
data(mtcars)
mtcars_scaled<-scale(mtcars)
distance_matrix <- dist(mtcars_scaled, method = "euclidean")
hc_complete <- hclust(distance_matrix, method = "complete")
hc_complete <- hclust(distance_matrix, method = "complete")
hc_complete <- hclust(distance_matrix, method = "complete")
data(mtcars)
mtcars_scaled <- scale(mtcars)
distance_matrix <- dist(mtcars_scaled, method = "euclidean")
hc_single <- hclust(distance_matrix, method = "single")
plot(hc_single, main="Dendogram hijerarhijskog klasterovanja", xlab="Automobili", sub="Single linkage", cex=0.7)
clusters <- cutree(hc_single, k = 3)
mtcars$Cluster <- clusters
print(mtcars)
save.image("C:\\Users\\PC\\Desktop\\Analiza podataka\\Automobili_SingleLinkage.R")
save.image("C:\\Users\\PC\\Desktop\\Analiza podataka\\Automobili_SingleLinkage.RData")
q()
data(mtcars)
mtcars_scaled <- scale(mtcars)
distance_matrix <- dist(mtcars_scaled, method="euclidan")
> distance_matrix <- dist(mtcars_scaled, method="euclidean")
distance_matrix <- dist(mtcars_scaled, method="euclidean")
distance_matrix <- dist(mtcars_scaled, method="euclidean")
hc_complete <- hclust(distance_matrix, method="complete")
plot(hc_complete,main="Dendogram hijerarhijskog klasterovanja", xlab="Automobili", sub="", cex=0.7)
clusters <- cutree(hc_complete, k=3)
mtcars$Cluster <- clusters
print(mtcars)
save.image("C:\\Users\\PC\\Desktop\\Analiza podataka\\Automobili_complete_linkage")
q()
install.packages("cluster")
install.packages("e1071")
library(cluster)
library(e1071)
set.seed(123)
x1 <- matrix(rnorm(40, mean = 2), ncol = 2)
x2 <- matrix(rnorm(40, mean = 3), ncol = 2)
x3 <- matrix(rnorm(40, mean = 4), ncol = 2)
x <- rbind(x1, x2, x3)
true_labels <- factor(rep(1:3, each = 20))
plot(x, col = true_labels, pch = 19, main = "Preklapanje oblaka")
d <- dist(x)
hc <- hclust(d, method = "complete")
clusters_hc <- cutree(hc, k = 3)
plot(x, col = clusters_hc, pch = 19, main = "Hijerarhijsko klasterovanje")
fuzzy_res <- cmeans(x, centers = 3, m = 2)
colors_rgb <- rgb(
  fuzzy_res$membership[,1],  # R - klaster 1
  fuzzy_res$membership[,2],  # G - klaster 2
  fuzzy_res$membership[,3]   # B - klaster 3
)
plot(x, col = colors_rgb, pch = 19, main = "Fuzzy klasterovanje")
load("C:\\Users\\PC\\Desktop\\Analiza podataka\\Oblaci_Fuzzy_HC_uporedni.RData")
save.image("C:\\Users\\PC\\Desktop\\Analiza podataka\\Oblaci_HC_Fuzzy")
